name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  check_version: 
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.extract_version.outputs.version }}
      SHOULD_PUBLISH: ${{ steps.check_git_tags.outputs.SHOULD_PUBLISH }}

    steps: 
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extracting the version
        id: extract_version
        run: |
          version=$(jq -r .version < package.json)
          echo "TAG=v$version" >> $GITHUB_OUTPUT

      - name: checking for previous releases with the same version.
        id: check_git_tags
        run: |
          TAG="${{ steps.extract_version.outputs.TAG }}"
          exists=$(git tag -l "$TAG")
          if [[ -n "$exists" ]];then
            echo "Tag already exists no need to publish, aborting..."
            echo "SHOULD_PUBLISH=false" >> $GITHUB_OUTPUT
          else
            echo "This version doesnot exits yet, releasing..."
            echo "SHOULD_PUBLISH=true" >> $GITHUB_OUTPUT
          fi

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: check_version 
    if: needs.check_version.outputs.SHOULD_PUBLISH == 'true'

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest 

      - name: Installing dependencies
        run: bun install

      - name: Publishing to npm
        run: |
          bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Creating and publishing a release 
        run: |
          echo '${{ toJSON(needs.check_version.outputs.TAG) }}'
          TAG="${{ needs.check_version.outputs.TAG }}"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git tag "$TAG"
          git push origin "$TAG"

      - name: Generate release notes
        run: |
          TAG="${{ needs.check_version.outputs.TAG }}"
          ./scripts/release-note.sh "$TAG"

      - name: Creating a release
        run: |
          TAG="${{ needs.check_version.outputs.TAG }}"
          gh release create "$TAG" --title "$TAG 🎉" -F ../ReleaseNotes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
