name: Publish to jsr
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest 

      - name: Extracting the version
        id: extract_version
        run: |
          version=$(jq -r .version < package.json)
          echo "TAG=v$version" >> $GITHUB_OUTPUT

      - name: checking for previous releases with the same version.
        run: |
          TAG="${{ steps.extract_version.outputs.TAG }}"
          exists=$(git tag -l "$TAG")
          if [[ -n "$exists" ]];then
            echo "Tag already exists no need to publish, aborting..."
            exit 0
          fi

      - name: Installing dependencies
        run: bun install

      - name: Publishing to jsr
        run: |
          bun publish 

      - name: Creating and publishing a release tag 
        run: |
          TAG="${{ steps.extract_version.outputs.TAG }}"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git tag "$TAG"
          git push origin "$TAG"

      - name: Creating a release
        run: |
          TAG="${{ steps.extract_version.outputs.TAG }}"
          gh release create "$TAG" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

